### ISSUE TITLE
Failed to run example

### ISSUE THREAD

**Issue by Kaspek2480** [xxDark/SSVM#26]
Exception in thread "main" java.lang.NoClassDefFoundError: dev/xdark/jlinker/ArenaAllocator
	at dev.xdark.ssvm.VirtualMachine.<init>(VirtualMachine.java:118)
	at Main$1.<init>(Main.java:15)
	at Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: dev.xdark.jlinker.ArenaAllocator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 3 more
	
	Tried to compile that with jdk 1.8 and jdk 17, i compiled manually and the problem appera
	
	
![image](https://github.com/xxDark/SSVM/assets/33702004/9766ff68-093f-4cca-b0ea-2ae1609bbf6e)

**Comment by Col-E** [comment]
As the exception states, you are missing JLinker: https://github.com/xxDark/jlinker
