### ISSUE TITLE
Exception when calling obfuscated jar method (on latest current commit d559ea9)

### ISSUE THREAD

**Issue by iocmet** [xxDark/SSVM#29]
```
Exception in thread "main" dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: a/replaced/package/replacedClassName.replacedMethodName(La/replaced/package/replacedClassName1;Ljava/lang/String;Ljava/lang/String;)V
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.invoke.InvocationUtil.invoke(InvocationUtil.java:40)
	at dev.xdark.ssvm.invoke.InvocationUtil.invokeVoid(InvocationUtil.java:48)
	at (package).Main.main(Main.java:34)
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: <main-package>/cy.<clinit>()V
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invokeVoid(DefaultInvocationOperations.java:36)
	at dev.xdark.ssvm.operation.VMOperations.invokeVoid(VMOperations.java:46)
	at dev.xdark.ssvm.operation.DefaultClassOperations.initialize(DefaultClassOperations.java:224)
	at dev.xdark.ssvm.operation.DefaultClassOperations.findClass0(DefaultClassOperations.java:513)
	at dev.xdark.ssvm.operation.DefaultClassOperations.findClass(DefaultClassOperations.java:245)
	at dev.xdark.ssvm.operation.VMOperations.findClass(VMOperations.java:56)
	at dev.xdark.ssvm.execution.asm.GetStaticProcessor.execute(GetStaticProcessor.java:28)
	at dev.xdark.ssvm.execution.asm.GetStaticProcessor.execute(GetStaticProcessor.java:22)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 5 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandleNatives.linkCallSite(Ljava/lang/Object;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/invoke/MemberName;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invokeVoid(DefaultInvocationOperations.java:36)
	at dev.xdark.ssvm.operation.VMOperations.invokeVoid(VMOperations.java:46)
	at dev.xdark.ssvm.operation.DefaultInvokeDynamicOperations.linkCall(DefaultInvokeDynamicOperations.java:88)
	at dev.xdark.ssvm.operation.VMOperations.linkCall(VMOperations.java:60)
	at dev.xdark.ssvm.execution.asm.InvokeDynamicLinkerProcessor.execute(InvokeDynamicLinkerProcessor.java:20)
	at dev.xdark.ssvm.execution.asm.InvokeDynamicLinkerProcessor.execute(InvokeDynamicLinkerProcessor.java:16)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 17 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandleNatives.linkCallSiteImpl(Ljava/lang/Class;Ljava/lang/invoke/MethodHandle;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/invoke/MemberName;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 27 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/CallSite.makeSite(Ljava/lang/invoke/MethodHandle;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/invoke/CallSite;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 34 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/BootstrapMethodInvoker.invoke(Ljava/lang/Class;Ljava/lang/invoke/MethodHandle;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 41 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/BootstrapMethodInvoker.invoke(Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 48 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandle.invoke(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 55 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/LambdaForm$MH.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.natives.MethodHandleNatives.lambda$init$8(MethodHandleNatives.java:156)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 62 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandle.invokeBasic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;III)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 66 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/LambdaForm$DMH.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;III)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.natives.MethodHandleNatives.lambda$init$8(MethodHandleNatives.java:156)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 73 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandle.linkToStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;IIILjava/lang/invoke/MemberName;)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 77 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: <main-package>/lz.a(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;III)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.natives.MethodHandleNatives.lambda$init$9(MethodHandleNatives.java:182)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 84 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandle.invoke(Ljava/lang/Object;I)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 88 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/LambdaForm$MH.invoke(Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.natives.MethodHandleNatives.lambda$init$8(MethodHandleNatives.java:156)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 95 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandle.invokeBasic(Ljava/lang/Object;I)J
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 99 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/LambdaForm$DMH.invokeVirtual(Ljava/lang/Object;Ljava/lang/Object;I)J
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.natives.MethodHandleNatives.lambda$init$8(MethodHandleNatives.java:156)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 106 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: java/lang/invoke/MethodHandle.linkToVirtual(Ljava/lang/Object;ILjava/lang/invoke/MemberName;)J
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 110 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: jdk/internal/reflect/ConstantPool.getLongAt(I)J
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.natives.MethodHandleNatives.lambda$init$9(MethodHandleNatives.java:182)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 117 more
Caused by: dev.xdark.ssvm.execution.PanicException: Uncaught VM error at: jdk/internal/reflect/ConstantPool.getLongAt0(Ljava/lang/Object;I)J
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:67)
	at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
	at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
	at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
	at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
	at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 121 more
Caused by: java.lang.ClassCastException: class me.coley.cafedude.classfile.constant.CpInt cannot be cast to class me.coley.cafedude.classfile.constant.CpLong (me.coley.cafedude.classfile.constant.CpInt and me.coley.cafedude.classfile.constant.CpLong are in unnamed module of loader 'app')
	at dev.xdark.ssvm.natives.ConstantPoolNatives.lambda$init$4(ConstantPoolNatives.java:81)
	at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
	... 128 more
```

I running it on java 11 because on 8 and 9 i gets other exceptions

**Comment by iocmet** [comment]
Oh, it is not SSVM issue, i modified jar, constant pool entries indexes changed and this method tries get int at specific index
